---
title: "About"
---

## Coverage

- MIS Quarterly
- Information Systems Research
- Journal of the Association for Information Systems
- European Journal of Information Systems
- Information Systems Journal

- International Conference on Information Systems

For ICIS 2025 import: wait for DBLP metadata (otherwise, we will have to link the DBLP anyway (for the url))

::: {.callout-note title="JSIS Special Issue" collapse=true}

- [x] [2025](https://www.sciencedirect.com/journal/the-journal-of-strategic-information-systems/vol/34/issue/2)
- [x] [2024](https://www.sciencedirect.com/special-issue/10P7VBSSM8G)
- [x] [2023](https://www.sciencedirect.com/special-issue/109CJ1SWF7T)
- [x] [2022](https://www.sciencedirect.com/journal/the-journal-of-strategic-information-systems/vol/31/issue/2)
- [x] [2021](https://www.sciencedirect.com/journal/the-journal-of-strategic-information-systems/vol/30/issue/4)
- [x] [2020](https://www.sciencedirect.com/journal/the-journal-of-strategic-information-systems/vol/29/issue/4)
- [x] [2019](https://www.sciencedirect.com/journal/the-journal-of-strategic-information-systems/vol/28/issue/2)

https://www.sciencedirect.com/search?pub=The+Journal+of+Strategic+Information+Systems&cid=271674&articleTypes=REV&lastSelectedFacet=articleTypes

:::

## Prior collections of literature reviews

SchryenWagnerBenlianEtAl2020, ParéTemplier2018, ParéEtAl2015, WagnerPresterRocheEtAl2021

## Definition

TODO

## Procedure

The `data/records.bib` serves as the main database.

### Community contribution

Describe Github process

### Harvest

### Screen

- colrev_status = rev_synthesized is used for literature-reviews
- colrev_status = rev_excluded is used for non-literature-reviews (adding a note)

with script; guidelines for documenting decisions

```sh
# screen with
colrev-cli-prescreen
```

### Update database

To update the pages and statistics, run

```sh
make update
```

## People

TODO

## License

TODO

## How to cite

TODO
